### ISSUE TITLE
AllophoneExtractor / JPhonemiser crashes for some words (in lexicon)

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#368]
Hi folks,

I was running the AllophoneExtractor on this sentence / file:

_Hanna Jaich_

(which is a name)

Both words are in my lexicon in $marybase/marytts-languages/marytts-lang-**lang**/lib/modules/<lang>/lexicon/**lang**.txt

<lang> is _de_ here.

Somehow _jaich_ seems to crash the whole process:

```
java.lang.Exception: The component AllophonesExtractor produced the following exception: 
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.IOException: Error message from server:
<html><body><h1>Internal server error</h1><p>Processing failed.<pre>java.lang.Exception: Module JPhonemiser_de: Problem processing the data.
    at marytts.server.Request.processOneChunk(Request.java:551)
    at marytts.server.Request.processOrLookupOneChunk(Request.java:385)
    at marytts.server.Request.process(Request.java:327)
    at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
    at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
    at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
    at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
    at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
    at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
    at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
    at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
    at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
    at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at marytts.modules.phonemiser.AllophoneSet.syllabify(AllophoneSet.java:554)
    at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:163)
    at marytts.language.de.JPhonemiser.phonemise(JPhonemiser.java:361)
    at marytts.language.de.JPhonemiser.process(JPhonemiser.java:244)
    at marytts.server.Request.processOneChunk(Request.java:549)
    ... 19 more
</pre></body></html>
    at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:397)
    at marytts.client.http.MaryHttpClient._process(MaryHttpClient.java:439)
    at marytts.client.MaryClient.process(MaryClient.java:653)
    at marytts.client.MaryClient.process(MaryClient.java:659)
    at marytts.tools.voiceimport.AllophonesExtractor.generateAllophonesFile(AllophonesExtractor.java:218)
    at marytts.tools.voiceimport.AllophonesExtractor.compute(AllophonesExtractor.java:150)
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:59125/process
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
    at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:388)
    ... 6 more
```

Calling 
_http://localhost:59125/process?INPUT_TEXT=jaich&INPUT_TYPE=TEXT&OUTPUT_TYPE=PHONEMES&LOCALE=de_
results in the same _internal server error_. 

Yet, _jaiche_, _jeich_, _jeuch_ have no problem being processed even though they're not in the lexicon ( they are made up from g2p/lts rules).

So, what might cause this error?
Is the specified lexicon the right one?

Thanks,

Benjamin

**Comment by psibre** [comment]
First of all, thanks for the report!

> Both words are in my lexicon in $marybase/marytts-languages/marytts-lang-lang/lib/modules//lexicon/lang.txt

That file is not directly used at all -- it serves as a resource for building the `marytts/language/de/lexicon` resouces.

You want to add your custom entries to `MARYBASE/user-dictionaries/userdict-de.txt` instead.

Unrelatedly,
> Somehow jaich seems to crash the whole process:

This is a known issue (see #342 and others) that has been fixed. This is what I get using the current master branch:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<phrase>
<t accent="H*" g2p_method="rules" ph="' j aI C" pos="ADJD">
jaich
<syllable accent="H*" ph="j aI C" stress="1">
<ph p="j"/>
<ph p="aI"/>
<ph p="C"/>
</syllable>
</t>
<boundary breakindex="5" tone="L-%"/>
</phrase>
</s>
</p>
</maryxml>
```

You can either downgrade to version 5.1.1 (before the bug was introduced), or pull from upstream.

**Comment by entenbein** [comment]
Hi,

just before you answered I came across #341, looks like the same. 

But thanks, I will update to the latest version!

**Comment by entenbein** [comment]
Hi,

I cloned the latest version from git today. Any idea why this kind of error is still occurring (but for other words) ? Again, a SAMPA transcription will be generated while I don't even use a SAMPA phoneset. How is that possible?

Thanks

**Comment by entenbein** [comment]
This problem also seems to delete transcriptions from my lexicon when using it for generating FST etc files with the TranscriptionTool. There is no error message or something commenting on that deletion whatsoever. But if you save the file after for some words the given transcription is missing. When trying to use the server to generate transcriptions 
```(http://localhost/process?INPUT_TEXT=[problematic word]&INPUT_TYPE=TEXT&OUTPUT_TYPE=PHONEMES&LOCALE=de)```
for those words the following error message is shown:

```
Internal server error

Processing failed.

java.lang.Exception: Module JPhonemiser_de: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:550)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:385)
	at marytts.server.Request.process(Request.java:327)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Found unknown symbol `?' in phonetic string `'?ap-g@-r uuh0 f n' -- ignoring.
	at marytts.modules.phonemiser.AllophoneSet.splitIntoAllophoneList(AllophoneSet.java:421)
	at marytts.modules.phonemiser.AllophoneSet.splitAllophoneString(AllophoneSet.java:340)
	at marytts.language.de.JPhonemiser.phonemise(JPhonemiser.java:339)
	at marytts.language.de.JPhonemiser.process(JPhonemiser.java:233)
	at marytts.server.Request.processOneChunk(Request.java:548)
	... 19 more
```

The problem is that there is a illegal phone in the transcription which is not part phone set, makes sense to ignore it. But where does the actually impossible, because never defined, phone come from? It is neither in the training data nor in the phone set obviously.

**Comment by seblemaguer** [comment]
you might have indicated that before but can you give some problematic word in order for me to try to reproduce this error?

**Comment by psibre** [comment]
@entenbein if by `[problematic word]` you mean *abgerufen*, I cannot reproduce your error. Which version/commit are you using?

> It is neither in the training data nor in the phone set obviously.

[The `?` *is* in the allophone set.](https://github.com/marytts/marytts/blob/bb2c683a4cd3ed2c4caab405801b48032e214364/marytts-languages/marytts-lang-de/src/main/resources/marytts/language/de/lexicon/allophones.de.xml#L74)

**Comment by entenbein** [comment]
@seblemaguer I got *Alsenborn* which produces this error.

@psibre, I know that *?* is in the SAMPA phone set. But I use my own phone set...

**Comment by psibre** [comment]
The `marytts.language.de.JPhonemiser` does quite a few different things to determine the pronunciation. If you have your own allophoneset, it's more than likely that it's an incomplete patch.
This sort of thing will be easier to debug in the near future, when we migrate the build to gradle and the pipeline from lexicon/phoneset to compiled dict and lts rules resources becomes transparent.

**Comment by entenbein** [comment]
I removed hard coded entries from 
```
marytts-languages/marytts-lang-de/src/main/resources/marytts/language/de/lexicon/denglish/PrefixLex.xml
```

I'm also skipping the tests when building the sources with maven. Anywhere else where the SAMPA transcriptions are hard coded into (re)sources?

Thanks
