### ISSUE TITLE
Fails under Ubuntu 18.04 with "Could not determine java version"

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [marytts/marytts#897]
I get this error trying to run Mary for the first time on a very light  Ubuntu 18.04 bionic, 64 bit, with just plain X & Openbox:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.2'.
```
I didn't have a problem under 16.04. Suggestions?

**Comment by psibre** [comment]
Could you please explain which command you're running, and how you installed or cloned MaryTTS?

**Comment by Lew-Rockwell-Fan** [comment]
I extracted the tar. CDed to the directory & ran:
./marytts --gui

**Comment by Lew-Rockwell-Fan** [comment]
Then I tried:
sudo ./marytts install:cmu-slt
but again got this output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.2'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by Lew-Rockwell-Fan** [comment]
This:
https://discuss.gradle.org/t/could-not-determine-java-version-from-9-0-1/24457
makes me wonder if upgrading gradle might fix it. Haven't figured out how to try that yet.

**Comment by seblemaguer** [comment]
could you try to do it with java 8 or 9?

**Comment by Lew-Rockwell-Fan** [comment]
8 is in the repo, so I can install it. Not immediately sure how to tell it which to use, but maybe that's in the internal docs.

**Comment by heruan** [comment]
Same for me, with Java 11. Does MaryTTS support Java 11? I cannot use 8 since latest versions of other dependencies requires Java 11 now.

**Comment by Lew-Rockwell-Fan** [comment]
Heruan, I'm not sure, & I know it sounds strange, but I'm thinking jre 8 & 11 can co-exist on the system and you can tell a program which to use. I haven't had time to dig into that enough to see if I'm right, let alone enough to figure out how to do it. I know I  did  something LIKE that some time in the past, but I'm not sure it was java - maybe it was python - & I don't recall what distro it was on. It looks to me like Mary does NOT support 11 yet, and it looks like Seblemaguer has the same suspicion.

**Comment by heruan** [comment]
Thank you @Lew-Rockwell-Fan for the feedback. Java 8 and 11 can co-exists, but the very same app where I need to use MaryTTS needs 11 so I hope Java 11 support will land on 6.0!

**Comment by psibre** [comment]
@heruan I'm curious which crazy, bleeding-edge app requires Java 11 and breaks on older versions. But whatever it is, why can't you just declare the MaryTTS dependencies there? You don't need to *build* MaryTTS on Java 11 to do that.

**Comment by heruan** [comment]
@psibre My own app does 🙂 You're right, I'll test if MaryTTS runs fine on Java 11!

**Comment by Lew-Rockwell-Fan** [comment]
OK. I went ahead and purged the default meta-package and all traces of 11, then installed openjdk-8-jre-headless & openjdk-8-jre. 11 didn't take any dependent programs with it, so I seem OK on that score. Now, it seems to work and have 1 U.S. English female voice installed. I  have forgotten the history of this installation but I assume it came with one preinstalled. I don't need root privs to get her to talk.  Been a while since I worked with this, and I'm going to have to study the docs again to figure  out how to install more voices. But jre 8 instead of 11 seems to be the trick. Thanks. 

I'm assuming you want to support 11, so this should remain open, albeit low priority, right?

**Comment by angelusroman** [comment]
what is the solution of it ?? I also get it when I 'm trying to run my ionic app ( sudo ionic cordova run anroid )

**Comment by candelrg** [comment]
Hello.
I don't know if it helps, but I had similar problems with Java programs I developed, and for me the problem cam from the fact that "java -version" changed its resulting text.

Let me explain:
- Before Java 9, "java -version" indicated something like "1.version.x".
- Since Java 9, "java -version" indicates something like "version.x.y".

So, to check Java version number, you'll have to test whether it starts by 1 or not.
I guess this is the problem you're facing...

**Comment by seblemaguer** [comment]
fixed by #923

**Comment by alexanderkoller** [comment]
Hi, we have [encountered this problem too](https://github.com/dialogos-project/dialogos/issues/207) when running DialogOS on Java 12.

Is your fix already part of a MaryTTS release? Maven Central still has 5.2 as the most recent version. If not, is there a reliable ETA for a release? Or would it be better if we built our own version of Mary from source?

@seblemaguer @psibre @akoehn

**Comment by timobaumann** [comment]
jitpack has the merge as https://jitpack.io/#marytts/marytts/1df2faf45a 
@alexanderkoller, you could check whether that solves our problem with recent javas.

**Comment by alexanderkoller** [comment]
I'll look into it.

**Comment by alexanderkoller** [comment]
It doesn't solve this easily, because `marytts-runtime` depends on `Jampack`, which is not world-readable on Jitpack. So back to the MaryTTS developers. :)

**Comment by timobaumann** [comment]
see https://github.com/dialogos-project/dialogos/issues/207#issuecomment-580350776 for how to fix this by pulling marytts from jitpack (which uses a different group-id which causes a lot of problems).
