### ISSUE TITLE
HTTP 404 for certain voice downloads

### ISSUE THREAD

**Issue by phtephanx** [marytts/marytts#932]
When currently trying to install certain voices using the `marytts-component-installer`, the download link does not work.

```
Starting installation
Now installing bits1...
Trying location http://mary.dfki.de/download/5.2/voice-bits1-5.2.zip...
java.io.IOException: Non-OK response code: 404 (Not Found)
	at marytts.tools.install.ComponentDescription$Downloader.run(ComponentDescription.java:715)
	at marytts.tools.install.ComponentDescription.download(ComponentDescription.java:361)
	at marytts.tools.install.ProgressPanel.run(ProgressPanel.java:215)
	at java.lang.Thread.run(Thread.java:748)
```

This occurs e.g. for `bits1` to `bits4`.
Links to other voices, e.g. `dfki-obadiah` are up and running.

**Comment by psibre** [comment]
This should be fixed (in part) by marytts/marytts-website#12 and deploying the voice distribution packages to GitHub as release assets.

**Comment by thomorl** [comment]
In a similar manner, most license texts are no longer shown in the "Reject/Accept License" dialogue box.

**Comment by phtephanx** [comment]
@thomorl Can this issue be closed? Do you mind opening another one if your issue still exists?

**Comment by witling** [comment]
What's the status of this issue? The installer still throws 404 errors for said voice

**Comment by seblemaguer** [comment]
We are in the progress of updating all the voices. Some issues remain but about 80% of the voices are ready. We need to finish this and publish everything to close this issue. So, hopefully, we will soon close this issue

**Comment by witling** [comment]
So is there currently a way of having a working bits4-de voice as showcased by the online demo? It would be great to have some guide on how to manually install voices or at least where to find them. I've taken a look at the `german-bits4` repository but downloading the releases only gives me some data files when I was expecting a jar.

**Comment by dev-2-4-h** [comment]
This issue still exists - where to find: voice-bits1-5.2.zip?
